### ISSUE TITLE
Feature request: Add .sls to supported formats

### ISSUE THREAD

**Issue by mmisztal1980** [wholroyd/vscode-jinja#4] opened 2016-07-15 14:39 UTC
This would provide support for SaltStack's state files using Jinja templates :)

**Comment by wholroyd** [comment] 2016-07-15 18:02
So I see two actual requests in this issue.
1. Adding the file extension (the easy part).
2. Recognizing the filepath that SaltStack uses prior to the YAML declaration (the hard part).

Visual Studio Code has issues with mixing languages, especially if you are mixing with a language that ships embedded with Code. See https://github.com/Microsoft/vscode/issues/1751 for more information on what I mean. This makes the second request harder to achieve without rewriting the YAML syntax, which I have thought about doing but have no time to do.

I can add the file extension in the next minor update (0.7), but full support of the syntax won't be there until I can find a way around the issue I just referenced.

**Comment by mmisztal1980** [comment] 2016-07-18 20:52
ad.1 that'd be great. How long till you release 0.7 ? (btw, can I set this locally until then? I'm unable to find the extension's file that contains the supported formats list)

**Comment by wholroyd** [comment] 2016-07-19 03:19
I just pushed 0.0.7 up to the marketplace for the .sls file format, so it's available now. :smile: 

All Code extensions will define their file extensions in the `package.json` file that sits at the root of the project. There the author can define what syntax should be associated with the extension. See https://github.com/wholroyd/vscode-jinja/blob/master/package.json#L52 as an example.

**Comment by wholroyd** [comment] 2016-11-10 02:57
As I mentioned over in #3 , I don't see myself being able to rewrite the YAML language to make this work and this is technically not a bug with the plugin, but a limitation of Code. As such, there is nothing I can really do about this until I get time or they fix language overrides in Code. I'm closing as Won't Fix for now.

**Closed as completed by wholroyd** 2016-11-10 02:57 UTC
Labels: enhancement, wontfix

**Comment by sebw** [comment] 2017-05-18 11:44
Despite running the latest version of the plugin, highlighting doesn't work for my state files.

In my settings.json I added this to get sls files highlighted as yaml:

`"files.associations": {"*.sls": "yaml"}`

**Comment by Silvenga** [comment] 2017-05-18 16:12
@sebw the default file associations were removed due to https://github.com/wholroyd/vscode-jinja/pull/15. `files.associations` is the proper way to apply custom associations overrides now.
